### ISSUE TITLE
pif.gsa.gov uses deprecated encryption for HTTPS

### ISSUE THREAD

**Issue by NoahKunin** [18F/pif-website#7]
The pif.gsa.gov application is still using SHA-1 for its entire certificate chain. SHA-1 has been deprecated by NIST, 18F, others, as it no longer provides adequate encryption.

Someone has to tell them to re-issue / re-deploy their certs as SHA-256 or above.

**Comment by stroupaloop** [comment]
This is a SalesForce built app, right? @NoahKunin 

Do you know who maintains pif.gsa.gov and the cert? Happy to provide a new cert :)

**Comment by NoahKunin** [comment]
@stroupaloop yep. I have no clue how any of that Salesforce happens, I've not been involved with Salesforce at GSA. Nada. But you sit next to someone who does... ;)

**Comment by NoahKunin** [comment]
Well, when you are sitting and not at your standing desk. :P

**Comment by stroupaloop** [comment]
Haha fair enough, I'll ping Garren and make sure we move on this. I actually saw that when I first started :)

**Comment by stroupaloop** [comment]
Don't we have a wildcard cert for *.gsa.gov? The SalesForce peeps should just be able to use this, right?

**Comment by stroupaloop** [comment]
Never mind, I was thinking of 18f.gov, apparently even gsa.gov isn't on HTTPS ...

**Comment by stroupaloop** [comment]
@NoahKunin does this issue delay pif.gov from going live since it sits on gsa.gov? This is something I'm resolving now, but the time horizon to fix this may be longer than anything I can do directly to pif.gov

**Comment by NoahKunin** [comment]
We now have a commitment from the Salesforce team to resolve this immediately. If we don't hear back in the next 10 business days, I will escalate with the GSA OCIO Information Security (IS) team.

**Comment by stroupaloop** [comment]
Just clearing out the Issues list here. GSA / SalesForce is updating the cert now and will be using the domain apply.pif.gov for the new URL. Should be resolved in the coming days (pinging them now).

Additionally, removing bug and hold as I believe the only thing remaining is the memo to formalize the ATO.

**Comment by stroupaloop** [comment]
@NoahKunin I'm removing the hold and bug tags as I believe the only thing remaining is formalizing the ATO via memo.

GSA / SalesForce is updating the cert and migrating the application to apply.pif.gov. Will follow up with them this week to confirm status.

**Comment by stroupaloop** [comment]
Should be resolved at this point.
